# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/prince/Desktop/assign_ptz_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_AssignCam(object):
    def setupUi(self, AssignCam, cameraList, assignedList, ptz_id):
        self.window = AssignCam
        self.cameraList = cameraList
        self.assignedList = assignedList
        self.ptz_id = ptz_id
        AssignCam.setObjectName("AssignCam")
        AssignCam.resize(270, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(AssignCam)
        self.verticalLayout.setObjectName("verticalLayout")
        self.assign_title_label = QtWidgets.QLabel(AssignCam)

        self.assign_title_label.setText("Assign PTZ " + ptz_id)
        # self.assign_title_label.setText(ptz_id)
        self.verticalLayout.addWidget(self.assign_title_label)
        self.usable_camera_list = QtWidgets.QListWidget(AssignCam)
        self.usable_camera_list.setObjectName("usable_camera_list")
        for item in cameraList:
            self.usable_camera_list.addItem(item.objectName())
        self.verticalLayout.addWidget(self.usable_camera_list)
        self.assign_btn = QtWidgets.QPushButton(AssignCam)
        self.assign_btn.setObjectName("assign_btn")

        self.assign_btn.clicked.connect(self.assign_ptz)
        self.verticalLayout.addWidget(self.assign_btn)
        self.cancel_btn = QtWidgets.QPushButton(AssignCam)
        self.cancel_btn.setObjectName("cancel_btn")
        self.cancel_btn.clicked.connect(self.window.close)
        self.verticalLayout.addWidget(self.cancel_btn)

        self.retranslateUi(AssignCam)
        QtCore.QMetaObject.connectSlotsByName(AssignCam)

    def assign_ptz(self):
        print("Assigning PTZ")
        cameraWidget = self.cameraList[self.usable_camera_list.currentRow()]
        cameraWidget.set_tracker(self.ptz_id)
        self.assignedList.append(self.ptz_id)
        self.assignedList.append(cameraWidget)

        self.window.close()

    def retranslateUi(self, AssignCam):
        _translate = QtCore.QCoreApplication.translate
        AssignCam.setWindowTitle(_translate("AssignCam", "Assign PTZ"))
        self.assign_btn.setText(_translate("AssignCam", "Assign"))
        self.cancel_btn.setText(_translate("AssignCam", "Cancel"))


class AssignCamDlg(QDialog):
    """Employee dialog."""

    def __init__(self, parent=None, cameraList=[], assignedList=[], ptz_id=''):
        super().__init__(parent)
        # Create an instance of the GUI

        self.ui = Ui_AssignCam()
        # Run the .setupUi() method to show the GUI
        self.ui.setupUi(self, cameraList=cameraList, assignedList=assignedList, ptz_id=ptz_id)
